version: '3.8'

services:
  db:
    image: postgres:latest
    volumes:
      - data_value:/var/lib/postgresql/data/
    restart: always
    env_file:
      - ./.env
    environment:
        POSTGRES_DB=${DB_NAME} 
        POSTGRES_USER=${POSTGRES_USER}
        POSTGRES_PASSWORD=${POSTGRES_PASSWORD}

  web:
    image: iskanderrrr/infra_actions:v1
    restart: always
    volumes:
      - static_value:/app/static/
      - media_value:/app/media/
    depends_on:
      - db
    env_file:
      - ./.env

  nginx:
    image: nginx:1.21.3-alpine
    ports:
      - "80:80"
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
      - static_value:/var/html/static/
      - media_value:/var/html/media/
    restart: always
    depends_on:
      - web

volumes:
  data_value:
  static_value:
  media_value: